version: "3"

services:
  app:
    build:
      context: .docker/php8.1-fpm/
      args:
        user: $USER
        uid: 1000
    restart: always
    container_name: app
    volumes:
      - ./:/var/www
      - ./.docker/php8.1-fpm/php.ini:/usr/local/etc/php/conf.d/local.ini

volumes:
  app:
    driver: local
