name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: curl, mbstring
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest --no-progress

      - name: Execute tests
        run: |
          vendor/bin/phpunit --verbose
